<?php

namespace Anaxago\CoreBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Returns all interest from a user
     * @param integer $id
     *
     * @return array
     */
	public function findAllByUser($id)
    {
    	$qb = $this->getEntityManager()->createQueryBuilder();
    	$qb->select('i')
	   ->from('AnaxagoCoreBundle:Interest', 'i')
	   ->where('i.idUser = ?1')
	   ->setParameter(1, $id);

        return $qb->getQuery()->getArrayResult();
    }
}
